[package]
name = "kf-protocol-dump"
edition = "2018"
version = "0.2.1"
authors = ["fluvio.io"]



[dependencies]
log = "0.4.8"
structopt = { version = "0.3.5" }
kf-protocol = { path = "../kf-protocol-core", package = "kf-protocol-core" }
kf-protocol-api = { path = "../kf-protocol-api", package = "kf-protocol-api" }
kf-protocol-message = { path = "../kf-protocol-message", package = "kf-protocol-message" }

flv-util = { version = "0.1.0" }