[package]
name = "kf-protocol-build"
version = "0.2.1"
authors = ["fluvio.io"]
edition = "2018"

[dependencies]
structopt = { version = "0.3.5", optional = true }
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.39"
tera = "0.11.20"
Inflector = "0.11.4"
rustfmt-nightly = { version = "1.4.10", optional = false}
textwrap = "0.11.0"

[[bin]]
name = "kfspec2code"
path = "src/bin/cli.rs"
doc = false
required-features = ["cli"]

[features]
cli = ["structopt"]